name: Update manifest

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - run: pip install requests beautifulsoup4
      - run: python scripts/update_manifest.py
      - name: Commit changes
        run: |
          git config --global user.name "pixelfirm-bot"
          git config --global user.email "bot@users.noreply.github.com"
          git add pixelfirm/manifest.json
          git commit -m "Update manifest [skip ci]" || echo "No changes"
          git push
