name: Update manifest

on:
  schedule:
    - cron: '0 2 * * *'  # daily at 02:00 UTC
  workflow_dispatch: {}

jobs:
  update-manifest:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
          # Install playwright browsers
          python -m playwright install --with-deps

      - name: Run manifest updater
        run: |
          python scripts/update_manifest.py

      - name: Commit manifest
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add pixelfirm/manifest.json || true
          if ! git diff --quiet --cached; then
            git commit -m "chore: update manifest (automated)"
            git push
          else
            echo "No changes to manifest"
          fi
